---
#SIW Backup job config file

#source and target directories
source: 'C:\Users'
destination: 'C:\Backup'

#Leave blank to use system time_zone
time_zone: ''

#list of backupjobs
backup_jobs:
    [
      'monday-1:30:00-full',
      'tuesday-1:30:00-diff'
    ]